# Copyright 2020 by the project contributors
# SPDX-License-Identifier: GPL-3.0-only
#
# Author(s): Pavel Benacek <pavel.benacek@gmail.com>

# Allow building on mater branch
branches:
    only:
    - master

# Select the OS to use
os:
    -linux
    -osx
    -windows

# Allow docker to run tests inside it
services:
    - docker

# Prepare the docker image in installation stage
install:
    - bash bootstrap.sh && docker build -t localhost/bsc-compiler --build-arg BJOBS=2.

# Run the bluespec test in container
script:
    - docker run -w /bluespec/bsc /bin/bash -c "cd examples/smoke_test && make smoke_test"

notifications:
  email: false

